[tool.poetry]
name = "1-2"
version = "0.1.0"
description = ""
authors = ["nalsher <nalsher@mail.ru>"]
readme = "README.md"
packages = [{include = "1"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
